# Generated by Django 2.2.4 on 2019-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20190827_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
