# Generated by Django 2.2.4 on 2019-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20190827_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(upload_to='cat/preview/'),
        ),
    ]
