# Generated by Django 2.2.4 on 2019-08-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20190827_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='url_video',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
