# Generated by Django 2.2.4 on 2019-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_auto_20190829_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='cat/preview/prew.png', upload_to='cat/preview/'),
        ),
    ]
