# Generated by Django 2.2.4 on 2019-08-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0015_auto_20190830_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='serie',
        ),
    ]
